### ISSUE TITLE
How is this different from the Eternita-S anit afk?

### ISSUE THREAD

**Issue by Endracion** [Fr4nsson/MyDalamudPlugins#1]
See title, there isn't much description surrounding it besides adding the repo and adding the plugins - whereas the other version uses ACT.

**Comment by Limiana** [comment]
In the fork keypress is being sent to game at a random intervals rather than at fixed one.
...but there is no point since there is no server-related action bound to ctrl key and afk timer fully handled client side, server doesn't receives any info about it at all. Would something like jump or walk be required, it would be absolutely necessary though.

**Comment by Fr4nsson** [comment]
The main difference is there's a GUI and you have more options to customize the keypress interval, the original always press CTRL at exactly 120 sec intervals if I remember correctly and I didn't like that the original spammed my dev log all the time. I just don't like to have something press at exact intervals, even though (anti-cheat wise) it does not matter atm.
